---
rvm:
  - 2.4.2

sudo: true

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y unzip
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - sudo mv terraform /usr/local/bin
  - rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - bundle install

before_script:
  - ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - bundle exec kitchen create

script:
  - bundle exec kitchen converge
  - bundle exec kitchen verify

after_script:
  - bundle exec kitchen destroy
